version: '3.8'

services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: sample
      MYSQL_CHARSET: utf8mb4
      MYSQL_COLLATION: utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    networks:
      - myapp-network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - myapp-network
    volumes:
      - redis-data:/data

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    environment:
      MYSQL_HOST: db
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: sample
      REDIS_URL: redis://redis:6379/0
    networks:
      - myapp-network

networks:
  myapp-network:
    driver: bridge
volumes:
  mysql-data:
    driver: local
  redis-data:
    driver: local
