default: &default
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: mysql
  host: db
  port: 3306

development:
  <<: *default
  database: sample

test:
  <<: *default
  database: sample

production:
  <<: *default
  database: sample
